### ISSUE TITLE
01 Hello OpenLab

### ISSUE THREAD

**Issue by Yikun** [Yikun/hello-openlab#1]
欢迎来到OpenLab的世界，本issue将跟踪如何完成在OpenLab上完成“Hello OpenLab”。

**Comment by Yikun** [comment]
OpenLab提供的核心能力之一，就是可以为项目提供计算资源（目前以虚拟机为主），用户可以通过配置来完成任务的定义，那么，先以"Hello OpenLab"为例介绍如何使用OpenLab的资源。
步骤说明：
#### 0) 申请资源。
https://github.com/theopenlab/openlab/issues/new/choose

#### 1) 安装APP。
https://github.com/apps/theopenlab-ci

#### 2) 配置JOB。
我们要通过配置文件，来告诉OpenLab，哪个项目需要跑什么脚本，具体如下：
1. **配置项目**，例如`https://github.com/Yikun/arm-openlab-test`的项目名称为`Yikun/arm-openlab-test`
2. **配置任务**，任务里定义了这个任务需要跑在哪个节点(nodeset)，需要跑哪个脚本。
3. **脚本**，配置脚本中需要执行哪些命令。
#### 举个栗子：
配置文件(.zuul.yaml)：
```
- project:
    name: Yikun/hello-openlab
    check:
      jobs:
        - hello-openlab-test

- job:
    name: hello-openlab-test
    parent: init-test
    description: |
      Hello OpenLab in OpenLab ARM cluster.
    run: .zuul/playbooks/arm-openlab-test/run.yaml
    nodeset: ubuntu-xenial-arm64
```
脚本文件(.zuul/playbooks/arm-openlab-test/run.yaml)：
```
- hosts: all
  tasks:
    - name: Hello OpenLab
      shell:
        cmd: |
          set -xe
          echo "Hello OpenLab"
        executable: /bin/bash
```
